spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/jmeter_report?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml

logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"

server:
  servlet:
    session:
      timeout: 14400
  port: 9123

# local
jmeter:
  jmeter-home: jmeter
  jmx-file-path: /Users/jixiang/Downloads/demo.jmx
  java-home: /Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home