spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/jmeter_report?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml

logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"

server:
  servlet:
    session:
      timeout: 14400
  port: 9123

jmeter:
  jmeter-home: /usr/local/apache-jmeter-5.6.2/bin/jmeter
  script-path: /home/getScriptPath.sh
  java-home: /usr/local/jdk1.8.0_231

ftp:
  host: localhost
  port: 21
  username: jixiang
  password: 123456
  file-home: /home/scripts